include: package:very_good_analysis/analysis_options.3.0.0.yaml
analyzer:
  exclude:
    - lib/l10n/*
    - lib/src/generated/
    - lib/gen/
linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
